const Anthropic = require('@anthropic-ai/sdk');

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

const generateGuide = async (guideData) => {
  try {
    const prompt = buildPrompt(guideData);
    
    const response = await anthropic.messages.create({
      model: 'claude-3-sonnet-20240229',
      max_tokens: 4000,
      temperature: 0.7,
      messages: [{ role: 'user', content: prompt }]
    });

    const generatedContent = response.content[0].text;
    return formatAsHTML(generatedContent, guideData);
    
  } catch (error) {
    console.error('Claude API error:', error);
    throw new Error('Failed to generate guide content');
  }
};

const buildPrompt = (data) => {
  return `You are an expert acting coach trained by Corey Ralston. Create a comprehensive, personalized audition preparation guide.

CHARACTER INFO:
- Character Name: ${data.characterName}
- Production: ${data.productionTitle}
- Production Type: ${data.productionType}
- Role Size: ${data.roleSize}
- Genre: ${data.genre}
${data.storyline ? `- Storyline: ${data.storyline}` : ''}
${data.characterBreakdown ? `- Character Breakdown: ${data.characterBreakdown}` : ''}
${data.callbackNotes ? `- Callback Notes: ${data.callbackNotes}` : ''}
${data.focusArea ? `- Focus Area: ${data.focusArea}` : ''}

SCENE TEXT:
${data.sceneText}

Create a comprehensive audition guide with these sections:
1. Project Overview
2. Character Breakdown  
3. Uta Hagen's 9 Questions
4. Scene Action & Physicality
5. Subtext & Emotional Depth
6. Character POV & Personalization
7. Bold Acting Choices
8. Moment Before & Button
9. Rehearsal & Experimentation
10. Action Plan Checklist

Make it personal, specific, and motivational. Focus on helping the actor book the role.`;
};

const formatAsHTML = (content, guideData) => {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${guideData.characterName}'s Audition Guide - PREP101</title>
    <style>
        body { 
            font-family: 'Inter', sans-serif; 
            line-height: 1.6; 
            color: #2d3748; 
            margin: 0; 
            padding: 2rem;
            background: linear-gradient(135deg, #2dd4bf 0%, #0891b2 100%);
        }
        .container { 
            max-width: 800px; 
            margin: 0 auto; 
            background: white;
            border-radius: 20px;
            padding: 3rem;
            box-shadow: 0 25px 80px rgba(0,0,0,0.1);
        }
        h1 { 
            color: #0891b2; 
            font-size: 2.5rem; 
            margin-bottom: 1rem; 
            text-align: center;
        }
        h2 { 
            color: #fb923c; 
            margin-top: 2rem; 
            font-size: 1.5rem;
        }
        .highlight { 
            background: linear-gradient(135deg, #f0fdfa 0%, #ecfdf5 100%);
            padding: 1.5rem; 
            border-left: 4px solid #2dd4bf; 
            margin: 1rem 0; 
            border-radius: 0.5rem;
        }
        .subtitle {
            text-align: center;
            color: #6b7280;
            font-size: 1.2rem;
            margin-bottom: 2rem;
        }
        p { margin-bottom: 1rem; }
        ul, ol { padding-left: 1.5rem; }
        li { margin-bottom: 0.5rem; }
    </style>
</head>
<body>
    <div class="container">
        <h1>${guideData.characterName}'s Audition Guide</h1>
        <div class="subtitle">${guideData.productionTitle} - ${guideData.productionType}</div>
        <div class="content">
            ${content.replace(/\n/g, '<br>')}
        </div>
        <div style="margin-top: 3rem; text-align: center; color: #6b7280; font-size: 0.9rem;">
            Generated by PREP101 - Custom Scene Analysis & Performance Coaching
        </div>
    </div>
</body>
</html>`;
};

module.exports = { generateGuide };
